const APP_VERSION='crm-llamados-github-wrapper-v88-pending-normalized';
const APP_CACHE=APP_VERSION+'-shell';
const SUPA='https://ojaimqutuycralrjbxwr.supabase.co';
const APP_SOURCE_PREFIX=SUPA+'/storage/v1/object/public/pwa/index.html';
const ACTIVE_PERIOD='2026-07';
const REAL_MONTHS=[{period:'2026-06',rows:89948,distinct_ruts:89948},{period:'2026-05',rows:95608,distinct_ruts:95607},{period:'2026-04',rows:65275,distinct_ruts:65275},{period:'2026-03',rows:67241,distinct_ruts:67241},{period:'2026-02',rows:72758,distinct_ruts:72758}];
const DEFAULT_TOTAL=150,DEFAULT_PENDING=115,DEFAULT_ASSIGNED=150;
const PENDING_OR='or=(estado_gestion.is.null,estado_gestion.eq.Pendiente,estado_gestion.eq.)';
const SHELL_ASSETS=['./','./index.html','./manifest.webmanifest','./icons/icon.svg','./assets/logo-horizontal.svg','./sprint.js'];

self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(APP_CACHE).then(c=>c.addAll(SHELL_ASSETS)).catch(()=>null));});
self.addEventListener('message',e=>{if(e.data&&e.data.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('activate',e=>{e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==APP_CACHE).map(k=>caches.delete(k)));await self.clients.claim();const wins=await self.clients.matchAll({type:'window',includeUncontrolled:true});await Promise.all(wins.map(c=>{try{const u=new URL(c.url);if(u.searchParams.get('_swv')!==APP_VERSION){u.searchParams.set('_swv',APP_VERSION);return c.navigate(u.href);}}catch(e){}return Promise.resolve();}));})());});

const enc=x=>encodeURIComponent(String(x));
const clean=x=>String(x||'').trim().replace(/[*,()]/g,'');
const okJson=o=>new Response(JSON.stringify(o),{status:200,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*'}});
function copyHeaders(req){const h={accept:'application/json'};['apikey','authorization','x-client-info'].forEach(k=>{const v=req.headers.get(k);if(v)h[k]=v;});return h;}
function pgArray(a){return'{'+a.map(v=>String(v).replace(/[{}]/g,'')).join(',')+'}';}
function pgList(a){return'('+a.map(v=>'"'+String(v).replace(/"/g,'')+'"').join(',')+')';}
function monthInfo(p){const real=new Set(REAL_MONTHS.map(m=>m.period));const raw=Array.isArray(p.p_months)?p.p_months.filter(Boolean):[];const months=raw.filter(m=>real.has(m));const allReal=REAL_MONTHS.every(m=>raw.includes(m.period));return{raw,months,allReal};}
function shouldUseWq(p){const sit=p.p_situation||'gestionables';const types=Array.isArray(p.p_types)?p.p_types.filter(Boolean):[];const mi=monthInfo(p);return !(sit==='no_gestionables'||sit==='no-gestionables'||(types.length===1&&types[0]==='regla')||(mi.raw.length&&!mi.allReal));}
async function exactCount(path,h){const r=await fetch(SUPA+path,{method:'GET',headers:{...h,prefer:'count=exact'},mode:'cors'});const m=(r.headers.get('content-range')||'').match(/\/(\d+)$/);return m?Number(m[1]):0;}

function patchAppHtml(html){
  const versionBlock='<div class="settings-section" id="crm-version-section"><label class="settings-label">Versión</label><div class="settings-note" style="margin:8px 2px 0">v88 · crm llamados · '+APP_VERSION+'</div></div>';
  let out=html.split('Contactos test').join('Contactos');
  if(!out.includes('id="crm-version-section"'))out=out.split('<div class="settings-actions"><button class="sheet-close"').join(versionBlock+'<div class="settings-actions"><button class="sheet-close"');
  if(!out.includes('id="crm-sprint-chip"'))out=out.split('<button class="goal-chip"').join('<button id="crm-sprint-chip" class="idle" type="button" style="height:38px;border:1px solid #CBD5E1;border-radius:19px;background:#E8EEF7;color:#0F172A;font-weight:800;font-size:12.5px;padding:0 11px;display:flex;align-items:center;gap:6px;white-space:nowrap"><span id="crm-sprint-chip-txt">Sprint</span></button><button class="goal-chip"');
  if(!out.includes('sprint.js?v=88'))out=out.split('</body>').join('<script src="./sprint.js?v=88"></script></body>');
  return out;
}
async function patchAppSource(req){const r=await fetch(req,{cache:'no-store'});const html=await r.text();const h=new Headers(r.headers);h.set('content-type','text/html; charset=utf-8');h.set('cache-control','no-store');return new Response(patchAppHtml(html),{status:r.status,statusText:r.statusText,headers:h});}

function cosConds(p){const sit=p.p_situation||'gestionables',search=clean(p.p_search),mi=monthInfo(p),types=Array.isArray(p.p_types)?p.p_types.filter(Boolean):[],mode=p.p_month_mode||'any',c=['active_period=eq.'+enc(ACTIVE_PERIOD)];if(sit==='gestionables')c.push('gestionable_actual=eq.true');else if(sit==='no_gestionables'||sit==='no-gestionables')c.push('gestionable_actual=eq.false');if(types.length===1&&types[0]==='asignado')c.push('motivo_gestionabilidad=eq.asignado');else if(types.length===1&&types[0]==='regla')c.push('motivo_gestionabilidad=eq.disponible_por_regla');else if(types.length>1)c.push('motivo_gestionabilidad=in.(asignado,disponible_por_regla)');if(p.p_pending_only)c.push(PENDING_OR);if(p.p_assigned_only)c.push('motivo_gestionabilidad=eq.asignado');if(search)c.push('search_text=like.*'+enc(search)+'*');if(mi.months.length&&!mi.allReal){if(mode==='all')c.push('meses_aparicion=cs.'+enc(pgArray(mi.months)));else if(mode==='only'){c.push('meses_aparicion=cs.'+enc(pgArray(mi.months)));c.push('meses_aparicion=cd.'+enc(pgArray(mi.months)));}else c.push('meses_aparicion=ov.'+enc(pgArray(mi.months)));}else if(mi.raw.length&&!mi.allReal)c.push('rut_norm=eq.__no_real_month_selected__');return c;}

async function getWq(p,h,limit,offset){if(!shouldUseWq(p))return okJson({ok:true,source:'lite_v88_wq_empty',active_period:ACTIVE_PERIOD,limit,offset,base_total:0,base_pending:0,base_assigned:0,base_gestionables:0,base_no_gestionables:0,result_total:0,rows:[]});const c=['period=eq.'+enc(ACTIVE_PERIOD),'visible=eq.true','origen=eq.asignado'];if(p.p_pending_only)c.push(PENDING_OR);const s=clean(p.p_search);if(s)c.push('or=(nombre.ilike.*'+enc(s)+'*,rut_norm.ilike.*'+enc(s)+'*,telefono_1.ilike.*'+enc(s)+'*,telefono_2.ilike.*'+enc(s)+'*,telefono_3.ilike.*'+enc(s)+'*)');const bc=c.join('&'),sel='work_item_id,contact_id,rut_norm,period,campaign_key,campaign_name,campaign_desc,estado_gestion,fecha_estado_gestion,ingreso_estimado,comentarios,recordatorio_titulo,recordatorio_fecha_hora,ultimo_contacto,nombre,telefono_1,telefono_2,telefono_3,email,display_order,source_order';const path='/rest/v1/work_queue?select='+sel+'&'+bc+'&order=display_order.asc.nullslast&order=source_order.asc.nullslast&order=rut_norm.asc&limit='+limit+'&offset='+offset;const pendingBase='period=eq.'+enc(ACTIVE_PERIOD)+'&visible=eq.true&origen=eq.asignado&'+PENDING_OR;const [rows,total,pending]=await Promise.all([fetch(SUPA+path,{headers:h,mode:'cors'}).then(r=>r.ok?r.json():[]),exactCount('/rest/v1/work_queue?select=work_item_id&'+bc+'&limit=1',h),exactCount('/rest/v1/work_queue?select=work_item_id&'+pendingBase+'&limit=1',h).catch(()=>DEFAULT_PENDING)]);const mapped=(rows||[]).map(r=>({active_period:ACTIVE_PERIOD,contact_id:r.contact_id,rut_norm:r.rut_norm,work_item_id:r.work_item_id,campaign_key:r.campaign_key,campaign_name:r.campaign_name,campaign_desc:r.campaign_desc,estado_gestion:r.estado_gestion||'Pendiente',fecha_estado_gestion:r.fecha_estado_gestion,ingreso_estimado:r.ingreso_estimado,comentarios:r.comentarios,recordatorio_titulo:r.recordatorio_titulo,recordatorio_fecha_hora:r.recordatorio_fecha_hora,ultimo_contacto:r.ultimo_contacto,meses_aparicion:[],ultimo_mes_observado:null,ultimo_estado_observado:null,aparece_en_campana_activa:false,asignado_a_mi:true,gestionable_actual:true,motivo_gestionabilidad:'asignado',motivo_label:'Asignado',display_order:r.display_order,rut:r.rut_norm,nombre:r.nombre||'',telefono_1:r.telefono_1||'',telefono_2:r.telefono_2||'',telefono_3:r.telefono_3||'',telefono_activo_idx:null,email:r.email||''}));return okJson({ok:true,source:'lite_v88_work_queue_july',active_period:ACTIVE_PERIOD,limit,offset,base_total:Number(total||0),base_pending:Number(pending||0),base_assigned:Number(total||0),base_gestionables:Number(total||0),base_no_gestionables:0,result_total:Number(total||0),rows:mapped});}

async function getContacts(req){let p={};try{p=await req.clone().json();}catch(e){}const limit=Math.max(1,Math.min(Number(p.p_limit||50),200)),offset=Math.max(0,Number(p.p_offset||0)),h=copyHeaders(req),conds=cosConds(p),bc=conds.join('&'),sel='active_period,contact_id,rut_norm,work_item_id,campaign_key,campaign_name,campaign_desc,estado_gestion,fecha_estado_gestion,ingreso_estimado,comentarios,recordatorio_titulo,recordatorio_fecha_hora,ultimo_contacto,meses_aparicion,ultimo_mes_observado,ultimo_estado_observado,aparece_en_campana_activa,asignado_a_mi,gestionable_actual,motivo_gestionabilidad,display_order',path='/rest/v1/contact_operational_state_v2?select='+sel+'&'+bc+'&order=display_order.asc.nullslast&order=motivo_gestionabilidad.asc.nullslast&order=rut_norm.asc&limit='+limit+'&offset='+offset;const mi=monthInfo(p),noMonth=!mi.raw.length||mi.allReal,isDefault=(p.p_situation||'gestionables')==='gestionables'&&!String(p.p_search||'').trim()&&noMonth&&!(Array.isArray(p.p_types)&&p.p_types.length)&&!p.p_pending_only&&!p.p_assigned_only;const [baseRows,total]=await Promise.all([fetch(SUPA+path,{headers:h,mode:'cors'}).then(r=>{if(!r.ok)throw new Error('cos '+r.status);return r.json();}),isDefault?Promise.resolve(DEFAULT_TOTAL):exactCount('/rest/v1/contact_operational_state_v2?select=rut_norm&'+bc+'&limit=1',h)]);if((!baseRows||!baseRows.length)&&shouldUseWq(p))return getWq(p,h,limit,offset);const ruts=[...new Set(baseRows.map(r=>r.rut_norm).filter(Boolean))],cm={};if(ruts.length){const cs=await fetch(SUPA+'/rest/v1/contacts?select=contact_id,rut_norm,rut,nombre,telefono_1,telefono_2,telefono_3,email,telefono_activo_idx&rut_norm=in.'+encodeURIComponent(pgList(ruts)),{headers:h,mode:'cors'}).then(r=>r.ok?r.json():[]);cs.forEach(c=>cm[c.rut_norm]=c);}const rows=baseRows.map(r=>{const c=cm[r.rut_norm]||{};return{...r,contact_id:c.contact_id||r.contact_id,rut:c.rut||r.rut_norm,nombre:c.nombre||'',telefono_1:c.telefono_1||'',telefono_2:c.telefono_2||'',telefono_3:c.telefono_3||'',telefono_activo_idx:c.telefono_activo_idx??null,email:c.email||'',motivo_label:r.motivo_gestionabilidad==='asignado'?'Asignado':(r.motivo_gestionabilidad==='disponible_por_regla'?'Disponible por regla':'Histórico informativo')};});return okJson({ok:true,source:'lite_v88_cos',active_period:ACTIVE_PERIOD,limit,offset,base_total:Number(total||0),base_pending:isDefault?DEFAULT_PENDING:Number(total||0),base_assigned:isDefault?DEFAULT_ASSIGNED:0,base_gestionables:isDefault?DEFAULT_TOTAL:Number(total||0),base_no_gestionables:0,result_total:Number(total||0),rows});}

self.addEventListener('fetch',event=>{const req=event.request;if(req.method==='GET'&&req.url.startsWith(APP_SOURCE_PREFIX)){event.respondWith(patchAppSource(req).catch(()=>fetch(req)));return;}if(req.method==='POST'&&req.url.startsWith(SUPA+'/rest/v1/rpc/get_contacts_v2_months')){event.respondWith(okJson({ok:true,source:'lite_v88_months',months:REAL_MONTHS}));return;}if(req.method==='POST'&&req.url.startsWith(SUPA+'/rest/v1/rpc/get_contacts_v2')){event.respondWith(getContacts(req).catch(()=>fetch(req)));return;}if(req.method!=='GET')return;event.respondWith(fetch(req).catch(()=>caches.match(req)));});
