-- EJECUTADO · Issue #12
-- Este rollback restauró la definición anterior de get_contacts_v2 después de abortar
-- el hotfix incorrecto que excluía el universo histórico disponible por regla.
-- La restauración fue verificada en PROD: result_total=61567, base_assigned=150,
-- marker page_first_v1.
