-- ABORTADO · Issue #12
-- Esta migración no debe aplicarse.
-- El enfoque reducía indebidamente los gestionables a asignados o gestionados por el usuario,
-- omitiendo el universo histórico disponible por regla.
-- El cambio aplicado en PROD fue revertido mediante la migración
-- rollback_bad_prod_eligibility_hotfix.
